services:
  # S3 Browser UI - Web interface to browse LocalStack S3 buckets
  s3browser:
    image: filebrowser/filebrowser:latest
    container_name: s3browser_ai
    ports:
      - "8081:80"  # Changed port to avoid potential conflicts
    volumes:
      - ./localstack_data:/srv/localstack_data
      - ./data:/srv/data
      - ./models:/srv/models
    environment:
      - FB_BASEURL=/
    networks:
      - bookiewand_bookiewand-network

  # GST Validation Services
  gst_validation_model_selection:
    build:
      context: .
      dockerfile: ai/gst_validation/Dockerfile.model_selection
    container_name: gst_validation_model_selection
    env_file:
      - ./ai/.env
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
      - AWS_ENDPOINT_URL=http://bookiewand-localstack:4566
    networks:
      - bookiewand_bookiewand-network
      
  gst_validation_training:
    build:
      context: .
      dockerfile: ai/gst_validation/Dockerfile.training
    container_name: gst_validation_training
    env_file:
      - ./ai/.env
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
      - AWS_ENDPOINT_URL=http://bookiewand-localstack:4566
    networks:
      - bookiewand_bookiewand-network

  gst_validation_inference:
    build:
      context: .
      dockerfile: ai/gst_validation/Dockerfile.inference
    container_name: gst_validation_inference
    env_file:
      - ./ai/.env
    ports:
      - "8001:8000"
    volumes:
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - bookiewand_bookiewand-network

  gst_validation_context_preprocessing:
    build:
      context: .
      dockerfile: ai/gst_validation/Dockerfile.context_preprocessing
    container_name: gst_validation_context_preprocessing
    env_file:
      - ./ai/.env
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - AWS_ENDPOINT_URL=http://bookiewand-localstack:4566
    networks:
      - bookiewand_bookiewand-network

  # Account Mapping Services
  account_mapping_model_selection:
    build:
      context: .
      dockerfile: ai/account_mapping/Dockerfile.model_selection
    container_name: account_mapping_model_selection
    env_file:
      - ./ai/.env
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
      - AWS_ENDPOINT_URL=http://bookiewand-localstack:4566
    networks:
      - bookiewand_bookiewand-network

  account_mapping_training:
    build:
      context: .
      dockerfile: ai/account_mapping/Dockerfile.training
    container_name: account_mapping_training
    env_file:
      - ./ai/.env
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
      - AWS_ENDPOINT_URL=http://bookiewand-localstack:4566
    networks:
      - bookiewand_bookiewand-network

  account_mapping_inference:
    build:
      context: .
      dockerfile: ai/account_mapping/Dockerfile.inference
    container_name: account_mapping_inference
    env_file:
      - ./ai/.env
    ports:
      - "8002:8000"
    volumes:
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - bookiewand_bookiewand-network

  account_mapping_context_preprocessing:
    build:
      context: .
      dockerfile: ai/account_mapping/Dockerfile.context_preprocessing
    container_name: account_mapping_context_preprocessing
    env_file:
      - ./ai/.env
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - AWS_ENDPOINT_URL=http://bookiewand-localstack:4566
    networks:
      - bookiewand_bookiewand-network

  # GST Account Combined Services
  gst_acc_model_selection:
    build:
      context: .
      dockerfile: ai/Dockerfile.gst_acc.model_selection
    container_name: gst_acc_model_selection
    env_file:
      - ./ai/.env
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
      - AWS_ENDPOINT_URL=http://bookiewand-localstack:4566
    networks:
      - bookiewand_bookiewand-network

  gst_acc_training:
    build:
      context: .
      dockerfile: ai/Dockerfile.gst_acc.training
    container_name: gst_acc_training
    env_file:
      - ./ai/.env
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
      - AWS_ENDPOINT_URL=http://bookiewand-localstack:4566
    networks:
      - bookiewand_bookiewand-network

networks:
  bookiewand_bookiewand-network:
    external: true

volumes:
  data:
